In [2]:
import pandas as pd
import numpy as np

Load dataset into pandas dataframe

In [3]:
df = pd.read_csv('data/sentiment-analysis.csv', delimiter=',')

# print head of dataframe
df.head()

  Text, Sentiment, Source, Date/Time, User ID, Location, Confidence Score
0  "I love this product!", Positive, Twitter, 202...
1  "The service was terrible.", Negative, Yelp Re...
2  "This movie is amazing!", Positive, IMDb, 2023...
3  "I'm so disappointed with their customer suppo...
4  "Just had the best meal of my life!", Positive...

The dataframe failed to parse the data correctly. We can see there are 7 columns. Let's solve this by splitting it manually. And clean the data

In [5]:
# split the columns 
df = df['Text, Sentiment, Source, Date/Time, User ID, Location, Confidence Score'].str.split(',', expand=True)

,0,1,2,3,4,5,6
0,"""I love this product!""",Positive,Twitter,2023-06-15 09:23:14,@user123,New York,0.85
1,"""The service was terrible.""",Negative,Yelp Reviews,2023-06-15 11:45:32,user456,Los Angeles,0.65
2,"""This movie is amazing!""",Positive,IMDb,2023-06-15 14:10:22,moviefan789,London,0.92
3,"""I'm so disappointed with their customer suppo...",Negative,Online Forum,2023-06-15 17:35:11,forumuser1,Toronto,0.78
4,"""Just had the best meal of my life!""",Positive,TripAdvisor,2023-06-16 08:50:59,foodie22,Paris,0.88

Columns were splitted successfully. We can see there right column names are not there, instead integers (0,1...n). This is because the split function does not have any contextual information to split the columns with their names. We can fix that by setting the columns ourselves.

In [7]:
df.columns = ['Text', 'Sentiment', 'Source', 'Date/Time','User ID', 'Location', 'Confidence Score']
df.head(5)

,Text,Sentiment,Source,Date/Time,User ID,Location,Confidence Score
0,"""I love this product!""",Positive,Twitter,2023-06-15 09:23:14,@user123,New York,0.85
1,"""The service was terrible.""",Negative,Yelp Reviews,2023-06-15 11:45:32,user456,Los Angeles,0.65
2,"""This movie is amazing!""",Positive,IMDb,2023-06-15 14:10:22,moviefan789,London,0.92
3,"""I'm so disappointed with their customer suppo...",Negative,Online Forum,2023-06-15 17:35:11,forumuser1,Toronto,0.78
4,"""Just had the best meal of my life!""",Positive,TripAdvisor,2023-06-16 08:50:59,foodie22,Paris,0.88

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98 entries, 0 to 97
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Text              96 non-null     object
 1   Sentiment         96 non-null     object
 2   Source            96 non-null     object
 3   Date/Time         96 non-null     object
 4   User ID           96 non-null     object
 5   Location          96 non-null     object
 6   Confidence Score  96 non-null     object
dtypes: object(7)
memory usage: 5.5+ KB

There are no nulls in this dataset. Because of the nature of the dataset, let's go ahead and perform related data cleaning processes.

In [10]:
# check unique values
# Unique values for 'Sentiment'

print(df['Sentiment'].unique())

[' Positive' ' Negative' nan]

In [11]:
# unique values for location
print(df['Location'].unique())

[' New York' ' Los Angeles' ' London' ' Toronto' ' Paris' ' San Francisco'
 ' Berlin' ' Sydney' ' Mumbai' ' Orlando' ' Chicago' nan]

In [16]:
df['Confidence Score'].head()

0    0.85
1    0.65
2    0.92
3    0.78
4    0.88
Name: Confidence Score, dtype: object

In [12]:
# strip extra whitespaces from columns
for col in df.columns:
    df[col] = df[col].str.strip()

In [17]:
# convert 'Date/Time' dtype to datetime
df['Date/Time'] = pd.to_datetime(df['Date/Time'], errors='coerce')

# convert 'Sentiment' to category
df['Sentiment'] = df['Sentiment'].astype('category')

# convert 'Confidence Score to float'
df['Confidence Score'] = df['Confidence Score'].astype('float64')

df.head(5)

,Text,Sentiment,Source,Date/Time,User ID,Location,Confidence Score
0,"""I love this product!""",Positive,Twitter,2023-06-15 09:23:14,@user123,New York,0.85
1,"""The service was terrible.""",Negative,Yelp Reviews,2023-06-15 11:45:32,user456,Los Angeles,0.65
2,"""This movie is amazing!""",Positive,IMDb,2023-06-15 14:10:22,moviefan789,London,0.92
3,"""I'm so disappointed with their customer suppo...",Negative,Online Forum,2023-06-15 17:35:11,forumuser1,Toronto,0.78
4,"""Just had the best meal of my life!""",Positive,TripAdvisor,2023-06-16 08:50:59,foodie22,Paris,0.88

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98 entries, 0 to 97
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Text              96 non-null     object
 1   Sentiment         96 non-null     category
 2   Source            96 non-null     object
 3   Date/Time         96 non-null     datetime64[ns]
 4   User ID           96 non-null     object
 5   Location          96 non-null     object
 6   Confidence Score  96 non-null     float64
dtypes: category(1), datetime64[ns](1), float64(1), object(4)
memory usage: 4.9+ KB

Now we can